### ISSUE TITLE
False-positives with -brute option

### ISSUE THREAD

**Issue by 0xhexmex** [caffix/amass#20]
I'm seeing that the -brute option is returning domains that don't appear to exist. This is the latest 1.2.0 release downloaded today.

```
# ./amass -brute -norecursive example.com
acceso.example.com
blue.example.com
activestat.example.com
02.example.com
18.example.com
3com.example.com
ftp.example.com
green.example.com
www.example.com
```

```
# host 02.example.com
Host 02.example.com not found: 3(NXDOMAIN)
# host 18.example.com
Host 18.example.com not found: 3(NXDOMAIN)
```

**Comment by caffix** [comment]
Thank you for the feedback! I finally managed to experience the same issue, and am looking into what could be causing this problem. Stay tuned!

**Comment by madaratech** [comment]
Might be bad name servers.. need to validate them before using and remove the bad one, once detected?

**Comment by caffix** [comment]
@madaratech, you were exactly right! The Alternate DNS servers were returns fake answers when you queried for a name that didn't exist. Instead of sending back zero answers (like other servers), Alternate DNS sent back an A record with the IP address of their primary DNS server (198.101.242.72), which is also listening for traffic on port 80 and 443! Looks like a scam.
